name: Build and deploy Django app to Azure Web App - UanFilms

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django collectstatic
        run: python manage.py collectstatic --noinput

      - name: Run Django migrations
        run: python manage.py migrate

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: django-app
          path: |
            .
            !env/
            !.venv/
            !antenv/
            !__pycache__/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for OIDC login
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: django-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_665EE990B5DD426CB6D10189E44045DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3EB70DF0B3464F5286F16BD39EBC46FE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8C2235148AF4460792A54CAC8AC71875 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'UanFilms'
          slot-name: 'Production'